name: crypton
version: '0.1.0'
summary: Encryption, decryption file application.
description: Encryption, decryption file application.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  crypton:
    command: crypton
    extensions: [gnome]
    plugs: [network, network-bind, home]

parts:
  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration
  crypton:
    build-packages: [curl]
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
