name: crypton
version: '0.1.0'
summary: Encryption/Decryption file application.
description: Encryption/Decryption file application.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  crypton:
    command: crypton
    extensions: [gnome]
    plugs: [network, network-bind]

parts:
  zenity:
    plugin: nil
    stage-packages:
      - zenity
  qarma-integration:
    plugin: nil
    stage-snaps:
      - qarma/18
    stage:
      - usr/bin/qarma
  crypton:
    build-packages: [curl]
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

layout:
  /usr/share/zenity:
    symlink: $SNAP/usr/share/zenity
